name: practice_project
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

  flutter_localizations:
    sdk: flutter

  # https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^2.2.1
  # https://github.com/flutterchina/dio
  dio: ^3.0.7
  # https://github.com/ReactiveX/rxdart
  rxdart: ^0.22.5
  # Dart https://github.com/Sky24n/common_utils
  common_utils: ^1.1.3
  # Flutter https://github.com/Sky24n/flustars
  flustars: 0.2.6+1
  # Flutter https://github.com/best-flutter/flutter_swiper
  flutter_swiper: ^1.1.6
  # https://github.com/flutter/plugins/tree/master/packages/url_launcher
  url_launcher: 5.2.7
  # https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.6.2+1
  # https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.5.4
  # https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 0.3.16
  # https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^2.1.2
  # https://github.com/fluttercommunity/flutter_sticky_headers
  sticky_headers: ^0.1.8+1
  # https://github.com/flutterchina/azlistview
  azlistview: ^0.1.2
  # https://github.com/aleksanderwozniak/simple_gesture_detector
  simple_gesture_detector: ^0.1.4
  # https://github.com/theyakka/fluro
  fluro: ^1.5.1
  # https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^1.1.3
  # https://github.com/Naddiseo/dart-sprintf
  sprintf: ^4.0.2
  # https://github.com/rrousselGit/provider
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter




# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/store/
    - assets/images/state/
    - assets/images/order/
    - assets/images/order/dark/
    - assets/images/login/
    - assets/images/goods/
    - assets/images/shop/
    - assets/images/account/
    - assets/images/statistic/

